### ISSUE TITLE
In caso di mancata connessone o risposta del data MongDb va in crash

### ISSUE THREAD

**Issue by Alexkill536ITA** [Alexkill536ITA/PGM_web#1]
`                client.connect(function(err, mogodb) {
                    if (err) {
                        res.redirect('/dasboard');
                    } else {
                        var mogodb = mogodb.db("Piccolo_Grande_Mondo");
                        mogodb.collection("Schede_PG").insertOne(PG_temp, function(err, res) {
                            if (err) {
                                console.log('[ERROR] Database insert FAIL');
                                res.render('Dasboard');
                            }
                            console.log("1 document inserted MongoDB");
                            dbMysql.query('UPDATE `utenti` SET `N_schede` =? WHERE `utenti`.`Id_discord`=?', [1,decoded.user], async () => {
                                console.log('1 document inserted MySQL');
                                res.render('Dasboard');
                            });
                        });
                        client.close();
                    }
                });
                res.redirect('/dasboard');`

code error File /controllrs/insert.js

**Comment by NetworkShark** [comment]
Metti anche il log dell'errore?

**Comment by Alexkill536ITA** [comment]
(node:19128) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at ServerResponse.header (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\response.js:170:12)
    at E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\app.js:92:9
    at Layer.handle_error (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\router\index.js:315:13)
    at E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\router\index.js:335:12)
    at next (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\router\layer.js:67:12)
E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\mongodb\lib\utils.js:668
          throw error;
          ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at ServerResponse.header (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\response.js:771:10)
    at ServerResponse.location (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\response.js:888:15)
    at ServerResponse.redirect (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\express\lib\response.js:926:18)
    at E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\controllers\insert.js:82:29
    at E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\mongodb\lib\utils.js:665:9
    at E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\mongodb\lib\mongo_client.js:224:23
    at connectCallback (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\mongodb\lib\operations\connect.js:366:5)
    at E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\mongodb\lib\operations\connect.js:433:14
    at Server.<anonymous> (E:\GDR\Bot Piccologrande mondo\Discord_Bot_PGM_Web\node_modules\mongodb\lib\topologies\server.js:230:11) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Alexkill536ITA** [comment]
il push lo fatto ora

**Comment by Alexkill536ITA** [comment]
Risolto
